import {
  Activity,
  Airplay,
  AlarmClockIcon,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowUp,
  Baby,
  BadgeAlert,
  Bold,
  Calendar,
  CalendarDays,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleUserRound,
  Clock,
  Cloud,
  Code,
  Copy,
  Database,
  Ear,
  Edit,
  Eye,
  EyeOff,
  Fan,
  Filter,
  FolderOpen,
  GalleryHorizontal,
  Github,
  Heart,
  Info,
  Italic,
  Lamp,
  LayoutPanelLeft,
  LifeBuoy,
  List,
  Loader2,
  LogOut,
  type LucideIcon,
  Mail,
  MenuSquare,
  MessageSquare,
  MoonStar,
  MoreVertical,
  Play,
  Plus,
  PlusCircle,
  Search,
  Settings,
  SortAsc,
  SortDesc,
  Sparkles,
  Star,
  Sun,
  Table,
  Terminal,
  Trash2,
  Underline,
  UserPlus,
  Users,
  X,
} from "lucide-react-native";
import { cssInterop } from "nativewind";

function interopIcon(icon: LucideIcon) {
  cssInterop(icon, {
    className: {
      target: "style",
      nativeStyleToProp: {
        color: true,
        opacity: true,
      },
    },
  });
}
interopIcon(Settings);
interopIcon(Sun);
interopIcon(MoonStar);
interopIcon(AlignJustify);
interopIcon(Activity);
interopIcon(Airplay);
interopIcon(AlarmClockIcon);
interopIcon(AlertCircle);
interopIcon(AlignRight);
interopIcon(Baby);
interopIcon(BadgeAlert);
interopIcon(Calendar);
interopIcon(CircleUserRound);
interopIcon(Database);
interopIcon(Ear);
interopIcon(Fan);
interopIcon(GalleryHorizontal);
interopIcon(Lamp);
interopIcon(Table);
interopIcon(ArrowDown);
interopIcon(ArrowUp);
interopIcon(ChevronDown);
interopIcon(LayoutPanelLeft);
interopIcon(MenuSquare);
interopIcon(Check);
interopIcon(ChevronsDownUp);
interopIcon(ChevronsUpDown);
interopIcon(Copy);
interopIcon(CalendarDays);
interopIcon(Sparkles);
interopIcon(Bold);
interopIcon(Italic);
interopIcon(Underline);
interopIcon(AlignLeft);
interopIcon(Info);
interopIcon(X);
interopIcon(Search);
interopIcon(ChevronRight);
interopIcon(ChevronLeft);
interopIcon(ChevronUp);
interopIcon(Cloud);
interopIcon(LifeBuoy);
interopIcon(LogOut);
interopIcon(Mail);
interopIcon(MessageSquare);
interopIcon(Plus);
interopIcon(PlusCircle);
interopIcon(UserPlus);
interopIcon(Users);
interopIcon(AlignCenter);
interopIcon(Terminal);
interopIcon(AlertTriangle);
interopIcon(Code);
interopIcon(CheckSquare);
interopIcon(FolderOpen);
interopIcon(Play);
interopIcon(MoreVertical);
interopIcon(Edit);
interopIcon(Eye);
interopIcon(EyeOff);
interopIcon(Filter);
interopIcon(Heart);
interopIcon(List);
interopIcon(Loader2);
interopIcon(SortAsc);
interopIcon(SortDesc);
interopIcon(Star);
interopIcon(Trash2);
interopIcon(Clock);

export {
  Activity,
  Airplay,
  AlarmClockIcon,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowUp,
  Baby,
  BadgeAlert,
  Bold,
  Calendar,
  CalendarDays,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleUserRound,
  Cloud,
  Code,
  Copy,
  Database,
  Ear,
  Edit,
  Eye,
  EyeOff,
  Fan,
  Filter,
  GalleryHorizontal,
  Heart,
  Info,
  Italic,
  Lamp,
  LayoutPanelLeft,
  LifeBuoy,
  List,
  Loader2,
  LogOut,
  Settings,
  Mail,
  MenuSquare,
  MessageSquare,
  MoonStar,
  MoreVertical,
  Plus,
  PlusCircle,
  Search,
  SortAsc,
  SortDesc,
  Sparkles,
  Star,
  Sun,
  Table,
  Terminal,
  Trash2,
  Underline,
  UserPlus,
  Users,
  X,
  Clock,
  FolderOpen,
  Play,
};
